### ISSUE TITLE
binary-install de-sync error

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#117]
I am still working on nailing down what produces this error, but occasionally my madlib install gets unhooked from its binaries (?)

```
Downloading release from https://github.com/madlib-lang/madlib/releases/download/v0.19.2/madlib-arm64-apple-darwin.tar.gz
Error: spawnSync ~/.config/yarn/global/node_modules/binary-install/node_modules/.bin/madlib ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at spawnSync (node:child_process:871:24)
    at Binary.run (~/.config/yarn/global/node_modules/binary-install/index.js:107:20)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/@madlib-lang/madlib/src/run.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync ~/.config/yarn/global/node_modules/binary-install/node_modules/.bin/madlib',
  path: '~/.config/yarn/global/node_modules/binary-install/node_modules/.bin/madlib',
  spawnargs: [ '-v' ]
}
```

**Comment by brekk** [comment]
I'll reopen this if I can reproduce
