### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#25]
When trying to run `scripts/build && scripts/run test -i .`, there is a persistent error when using node < 13.0.0

```
Error: Cannot find module 'fs/promises'
Require stack:
- /Users/brekk/work/madlib/tools/test-runner/dist/test-runner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/brekk/work/madlib/tools/test-runner/dist/test-runner.js:2:166
    at Object.<anonymous> (/work/madlib/tools/test-runner/dist/test-runner.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

Likely we should use a shim for `fs/promises` or we should mandate a minimum version number for the node binary.

**Comment by brekk** [comment]
This can be tested with `nvm`, I found the error goes away when using 13.0.0 +

**Comment by aboeglin** [comment]
I can also rewrite it to only use fs. Although I plan on rewriting it soon in pure madlib, and it will then only use Wish.

**Comment by aboeglin** [comment]
Still haven't got to that yet. But the plan looks like this:
- properly implement some basic system functions in prelude ( readFile, writeFile and the like )
- figure a solution for dealing with child_process stuff
- rewrite the test runner fully in madlib

That might take a while, so maybe in between we could just import `fs` instead of `fs/promises` functions and promisify them.

**Comment by brekk** [comment]
Pretty sure this can be closed.
